# This is a workflow that is manually triggered to deploy given crabserver tag to given k8s host

name: CRABServer deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'CRABServer tag to deploy:'
        required: true
      hostName:
        description: 'Host where given tag should be deployed:'
        required: true   
        default: preprod

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke crabserver deployment
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: '{ "test1": "test1", "test2" : "test2" }'
        
